# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/shuij/Documents/Projects/CpuDesign/ResearchClass/ResearchClass.srcs/sources_1/ip/ClkPll/ClkPll.xci
# IP: The module: 'ClkPll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/shuij/Documents/Projects/CpuDesign/ResearchClass/ResearchClass.gen/sources_1/ip/ClkPll/ClkPll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkPll'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/shuij/Documents/Projects/CpuDesign/ResearchClass/ResearchClass.gen/sources_1/ip/ClkPll/ClkPll.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkPll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/shuij/Documents/Projects/CpuDesign/ResearchClass/ResearchClass.gen/sources_1/ip/ClkPll/ClkPll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkPll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/shuij/Documents/Projects/CpuDesign/ResearchClass/ResearchClass.srcs/sources_1/ip/ClkPll/ClkPll.xci
# IP: The module: 'ClkPll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/shuij/Documents/Projects/CpuDesign/ResearchClass/ResearchClass.gen/sources_1/ip/ClkPll/ClkPll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkPll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/shuij/Documents/Projects/CpuDesign/ResearchClass/ResearchClass.gen/sources_1/ip/ClkPll/ClkPll.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkPll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/shuij/Documents/Projects/CpuDesign/ResearchClass/ResearchClass.gen/sources_1/ip/ClkPll/ClkPll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClkPll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
