# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/soc_top.xdc

# IP: ip/data_ram/data_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_ram || ORIG_REF_NAME==data_ram} -quiet] -quiet

# IP: ip/inst_ram/inst_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inst_ram || ORIG_REF_NAME==inst_ram} -quiet] -quiet

# XDC: c:/Users/shuij/Documents/Projects/CpuDesign/mycpu/mycpu.gen/sources_1/ip/data_ram/data_ram_ooc.xdc

# XDC: c:/Users/shuij/Documents/Projects/CpuDesign/mycpu/mycpu.gen/sources_1/ip/inst_ram/inst_ram_ooc.xdc
